package:
    path: "/vendor/almasaeed2010/adminlte"

js:
    main:
        "AdminLTE.min.js": "/dist/js/adminlte.min.js"

css:
    main:
        "AdminLTE.min.css": "/dist/css/adminlte.min.css"

images: "/dist/img"

# Plugins from adminlte plugins folders
plugins:
    - "/plugins/bootstrap"
    - "/plugins/bootstrap4-duallistbox"
    - "/plugins/bootstrap-colorpicker"
    - "/plugins/bootstrap-slider"
    - "/plugins/bootstrap-switch"
    - "/plugins/bs-custom-file-input"
    - "/plugins/chart.js"
    - "/plugins/datatables"
    - "/plugins/datatables-autofill"
    - "/plugins/datatables-bs4"
    - "/plugins/datatables-buttons"
    - "/plugins/datatables-colreorder"
    - "/plugins/datatables-fixedcolumns"
    - "/plugins/datatables-fixedheader"
    - "/plugins/datatables-keytable"
    - "/plugins/datatables-responsive"
    - "/plugins/datatables-rowgroup"
    - "/plugins/datatables-rowreorder"
    - "/plugins/datatables-scroller"
    - "/plugins/datatables-select"
    - "/plugins/daterangepicker"
    - "/plugins/ekko-lightbox"
    - "/plugins/fastclick"
    - "/plugins/filterizr"
    - "/plugins/flag-icon-css"
    - "/plugins/flot"
    - "/plugins/flot-old"
    - "/plugins/fontawesome-free"
    - "/plugins/fullcalendar"
    - "/plugins/fullcalendar-bootstrap"
    - "/plugins/fullcalendar-daygrid"
    - "/plugins/fullcalendar-interaction"
    - "/plugins/fullcalendar-timegrid"
    - "/plugins/icheck-bootstrap"
    - "/plugins/inputmask"
    - "/plugins/ion-rangeslider"
    - "/plugins/jquery"
    - "/plugins/jquery-knob"
    - "/plugins/jquery-mapael"
    - "/plugins/jquery-mousewheel"
    - "/plugins/jquery-ui"
    - "/plugins/jquery-validation"
    - "/plugins/jqvmap"
    - "/plugins/jsgrid"
    - "/plugins/jszip"
    - "/plugins/moment"
    - "/plugins/overlayScrollbars"
    - "/plugins/pace-progress"
    - "/plugins/pdfmake"
    - "/plugins/popper"
    - "/plugins/raphael"
    - "/plugins/select2"
    - "/plugins/select2-bootstrap4-theme"
    - "/plugins/sparklines"
    - "/plugins/summernote"
    - "/plugins/sweetalert2"
    - "/plugins/sweetalert2-theme-bootstrap-4"
    - "/plugins/tempusdominus-bootstrap-4"
    - "/plugins/toastr"
